/* ═══════════════════════════════════════════════════════════════════════
 *  FIRST-RUN SEED
 *  ---------------------------------------------------------------------
 *  Builds the Gazette Engine's opening state by READING THE LIVE SITE FILES
 *  rather than by inventing anything:
 *
 *    membership.html  ->  the Membership roll
 *    app.js           ->  the Probationary Roster (probationaryRoster array)
 *    shame.html       ->  Wall of Shame entries, as notes against the member
 *
 *  Events are declared here explicitly, because the events page states several
 *  of them loosely ("Summer 2025", "as warranted") and a date the Society has
 *  not settled must be stored as unsettled, never guessed.
 *
 *  Run:  node gazette/seed.mjs > gazette/seed.sql
 *        npx wrangler d1 execute pwsow-gazette --remote --file=gazette/seed.sql
 *
 *  Safe to re-run: every insert is INSERT OR IGNORE keyed on slug.
 * ═══════════════════════════════════════════════════════════════════════ */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');

const q = s => s === null || s === undefined ? 'NULL' : `'${String(s).replace(/'/g, "''")}'`;
const slugify = s => s.toLowerCase()
  .replace(/&[a-z]+;/g, ' ')
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-|-$/g, '');

const out = [];
const say = l => out.push(l);

say('-- Generated by gazette/seed.mjs — do not edit by hand.');
say('-- Re-running is safe; every insert is INSERT OR IGNORE.');
say('');

/* ── The Membership roll, from membership.html ─────────────────────── */
const membership = read('membership.html');
const cardRe = /<div class="member-name">([^<]+)<\/div>\s*<div class="member-since">([^<]*)<\/div>/g;
const members = [];
let m;
while ((m = cardRe.exec(membership)) !== null) {
  members.push({ name: m[1].trim(), role: m[2].trim() });
}
if (!members.length) throw new Error('No member cards parsed — has membership.html changed shape?');

// Photos are /images/<slug>.jpg by the site's own convention.
const imagesDir = fs.readdirSync(path.join(ROOT, 'images'));
const photoFor = slug => {
  const hit = imagesDir.find(f => f === slug + '.jpg' || f === slug + '.png');
  return hit ? '/images/' + hit : null;
};

say('-- The Membership roll (' + members.length + ' entries, parsed from membership.html)');
for (const mem of members) {
  const slug = slugify(mem.name);
  // Jordan's induction is dated and recorded; everyone else's tenure predates
  // the Engine, so their standing_since is left null rather than invented.
  const isJordan = /steltenpohl/i.test(slug);
  const status = isJordan ? 'Associate Member' : 'Member';
  const since = isJordan ? '2026-07-11' : null;
  say(`INSERT OR IGNORE INTO members (name, slug, status, role, photo, standing_since, on_public_site) VALUES (${q(mem.name)}, ${q(slug)}, ${q(status)}, ${q(mem.role || null)}, ${q(photoFor(slug))}, ${q(since)}, 1);`);
}
say('');

/* ── The Probationary Roster, from the array in app.js ─────────────── */
const appjs = read('app.js');
const arrMatch = appjs.match(/const probationaryRoster = (\[[\s\S]*?\n\]);/);
if (!arrMatch) throw new Error('probationaryRoster not found in app.js');
// Our own file, our own literal — evaluating it is how we stay in step with it.
const roster = eval(arrMatch[1]);

// When each aspirant's present standing began. These are dates the Society has
// actually recorded; nothing here is estimated.
const STANDING_SINCE = {
  'mr-payton-marki':   '2023-01-01',   // "a pledge of this Society since 2023"
  'mr-thomas-kavanagh':'2020-01-01',   // six years of asking, as of 2026
  'mr-john-kavanagh':  '2020-01-01',
  'mr-paul-kavanagh':  '2026-09-05'    // the day he was entered on the roll
};

say('-- The Probationary Roster (' + roster.length + ' aspirants, parsed from app.js)');
for (const p of roster) {
  const slug = slugify(p.name);
  const region = String(p.region || '').replace(/&mdash;/g, '—').replace(/&middot;/g, '·');
  say(`INSERT OR IGNORE INTO members (name, slug, status, region, sponsor, recognized_date, standing_since, photo, notes, on_public_site) VALUES (${q(p.name)}, ${q(slug)}, ${q(p.standing)}, ${q(region)}, ${q(p.sponsor)}, ${q(p.recognizedDate)}, ${q(STANDING_SINCE[slug] || null)}, ${q(p.image)}, ${q(p.commodoreObserves)}, 1);`);
}
say('');

/* ── Wall of Shame, from shame.html ────────────────────────────────── */
const shame = read('shame.html');
const shameRe = /<div class="offender-stamp">([^<]+)<\/div>[\s\S]*?<div class="offender-name">([^<]+)<\/div>/g;
const shameEntries = [];
let s;
while ((s = shameRe.exec(shame)) !== null) {
  shameEntries.push({ verdict: s[1].trim(), name: s[2].trim() });
}
if (shameEntries.length) {
  say('-- Wall of Shame standing, recorded against the member (' + shameEntries.length + ' entries)');
  for (const e of shameEntries) {
    say(`UPDATE members SET notes = COALESCE(notes || ' | ', '') || ${q('Wall of Shame: ' + e.verdict)} WHERE slug = ${q(slugify(e.name))};`);
  }
} else {
  say('-- Wall of Shame: no entries matched the expected markup; seed by hand if needed.');
}
say('');

/* ── Events ────────────────────────────────────────────────────────── */
/* Declared, not scraped. The events page states several of these loosely and
   an unsettled date must be stored as unsettled. confirmed = 0 is what makes
   the Commodore's Desk raise it as blocking. */
const EVENTS = [
  { name: 'The Great Northern Open MMXXVI', date: '2026-07-11', time: '12:00', venue: 'Pine Valley Golf Course, Marathon, Wisconsin', confirmed: 1, covered: '2026-07-27', notes: 'Champions: Matthew Gelhar, James Baranowski, Curtis Engelbrecht. Team IV, -8*, a man short.' },
  { name: 'The Ohio Outing',                date: '2026-10-18', time: null,    venue: null, confirmed: 0, covered: null, notes: 'Proposed by Mr. Paul Kavanagh. Grounds and tee times NOT yet settled. Jackets before the Council.' },
  { name: 'The Curling Classic',            date: null,         time: null,    venue: 'Wausau, Wisconsin', confirmed: 0, covered: null, notes: 'Triple Crown, Leg III. Induction rights may be earned on the ice.' },
  { name: 'The Grand Croquet Classic',      date: null,         time: null,    venue: 'Greenwood Hills Country Club', confirmed: 0, covered: null, notes: 'Round robin, knockout finals, Best Dressed Lady.' },
  { name: 'Society Meeting & Tasting',      date: null,         time: null,    venue: null, confirmed: 0, covered: null, notes: 'Monthly, per membership availability.' },
  { name: 'Induction Ceremony',             date: null,         time: null,    venue: 'The Sacred Grounds, Wausau', confirmed: 0, covered: null, notes: 'As warranted.' }
];
say('-- Events (' + EVENTS.length + ') — unsettled dates stored as unsettled');
for (const e of EVENTS) {
  say(`INSERT OR IGNORE INTO events (name, slug, event_date, event_time, venue, confirmed, covered_at, notes) VALUES (${q(e.name)}, ${q(slugify(e.name))}, ${q(e.date)}, ${q(e.time)}, ${q(e.venue)}, ${e.confirmed}, ${q(e.covered)}, ${q(e.notes)});`);
}
say('');

/* ── The three dispatches already published ────────────────────────── */
const PUBLISHED = [
  { slug: 'steltenpohl-induction', kicker: 'An Induction',     title: 'Seventy-One Days',              persona: 'junior-golf-reporter',        byline: 'Mr. Barnaby Prescott' },
  { slug: 'ohio-outing',           kicker: 'The Ohio Outing',  title: 'The Society Goes South',        persona: 'junior-golf-reporter',        byline: 'Mr. Barnaby Prescott' },
  { slug: 'marki-contentment',     kicker: 'A Standing Matter',title: 'The Contentment of Mr. Marki',  persona: 'wall-of-shame-correspondent', byline: 'Mr. Edmund Vance' }
];
say('-- Already published, so the Engine does not offer to write them again');
for (const a of PUBLISHED) {
  say(`INSERT OR IGNORE INTO articles (slug, kind, persona, byline, kicker, title, status, approved_at, approved_by, published_at) VALUES (${q(a.slug)}, 'dispatch', ${q(a.persona)}, ${q(a.byline)}, ${q(a.kicker)}, ${q(a.title)}, 'published', datetime('now'), 'seed', datetime('now'));`);
}
say('');

say("INSERT OR IGNORE INTO settings (key, value) VALUES ('seeded_at', datetime('now'));");
say("INSERT OR IGNORE INTO settings (key, value) VALUES ('stale_days', '90');");

process.stdout.write(out.join('\n') + '\n');
